(* @NESTEDCOMMENTS := 'No' *)
(* @PATH := '\/core' *)
(* @OBJECTFLAGS := '0, 8' *)
TYPE LogBufferHandle :
STRUCT
    BufferAddress: POINTER TO BYTE;
    BufferSize: DINT;
    BufferEndAddress: POINTER TO BYTE;
    BufferWritePointer: DINT;
    BufferReadPointer: DINT;
    BufferOverflow: DINT;
    MagicByte: BYTE := MAGIC_BYTE_V1_LITTLE_ENDIAN;
END_STRUCT
END_TYPE

(* @END_DECLARATION := '0' *)
